### PR TITLE
Added isDivisibleBy

### PR DESCRIPTION
**Pull request by RishabAgarwal**

### CODE REVIEW

**Comment by RishabAgarwal** [comment]
@parasg1999 I made the changes you asked for. Take a look.

**Comment by parasg1999** [comment]
LGTM. Will request @rubiin to view it.

**Comment by rubiin** [comment]
@RishabAgarwal fix the merge conflicts

**Comment by rubiin** [comment]
the tests are failing . please ensure everything works before push @RishabAgarwal

**Comment by RishabAgarwal** [comment]
@rubiin ya sorry about that...

**Comment by rubiin** [comment]
looks good LGTM

**Pull request merged**
