### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by RishabAgarwal**
Added Description till **`isD*`**. #23

### CODE REVIEW

**Comment by RishabAgarwal** [comment]
> The table boundaries need to be corrected.

@parasg1999 could you explain what exactly to do?

**Comment by parasg1999** [comment]
@RishabAgarwal Seems like you've forgotten to add `|` for table boundaries

**Comment by rubiin** [comment]
you can now go along with other documentation if you like

**Comment by rubiin** [comment]
also be sure to ask to change the status of documentation done in the tracking issue

**Pull request merged**
